###
POST http://localhost:8000/fingerprint_enroll
Content-Type: application/json

{
    "fingerprint_id_real": "1212",
    "status": "enrolled"
}

###
POST http://localhost:8000/fingerprint_login
Content-Type: application/json

{
    "fingerprint_id_real": "1212",
    "confidence": 100
}