"""fingerprint id real

Revision ID: 0d750bab8482
Revises: a013c4be2c75
Create Date: 2025-05-29 20:33:50.847615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d750bab8482'
down_revision: Union[str, None] = 'a013c4be2c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operators', sa.Column('fingerprint_id_real', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operators', 'fingerprint_id_real')
    # ### end Alembic commands ###
